//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.19072
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParserImpl.Xml {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class XmlResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal XmlResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Portable.Parser.Xml.XmlResources", typeof(XmlResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///doc: decl comments element comments;
        ///
        ///decl: &apos;&lt;?xml&apos; attrs &apos;?&gt;&apos;;
        ///
        ///comments: comment*;
        ///element: &apos;&lt;&apos; name attrs &apos;/&gt;&apos; | (&apos;&gt;&apos; elContent &apos;&lt;/&apos; name &apos;&gt;&apos;);
        ///attrs: attr*;
        ///attr: name &apos;=&apos; &apos;&quot;&apos; avalue &apos;&quot;&apos;;
        ///elContent: (comment | cdata | element | text)*;
        ///cdata: &apos;&lt;![CDATA[&apos; dtext &apos;]]&gt;&apos;;
        ///comment: &apos;&lt;!--&apos; ctext &apos;--&gt;&apos;;
        ///
        ///ctext: &quot;(([^\-])|([\-][^\-])|([\-][\-][^\&gt;]))*&quot; ;
        ///dtext: &quot;(([^\]])|([\]][^\]])|([\]][\]][^\&gt;]))*&quot; ;
        ///text: &quot;[^&lt;]+&quot;;
        ///name: namePrefix identifier;
        ///namePrefix: (identifier &apos;:&apos;)?;
        ///identifier: &quot;[_a [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string OldXmlDocumentGrammar {
            get {
                return ResourceManager.GetString("OldXmlDocumentGrammar", resourceCulture);
            }
        }
    }
}
